### PR TITLE
Add cowplot and other requirements to shiny dockerfile

### LINKED ISSUE #13: Look for causaleffect dependency
https://github.com/hirscheylab/ddh/blob/5213ad2b48bef9f2d97e49df7c3e5fd33ab324ff/Dockerfile.shiny#L14

### PR DESCRIPTION
**Pull request by johnbradley**
Adds the following to the docker file used to run the shiny webserver:
- cowplot used in [app.R](https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/app.R#L14)
- digest used in [app.R](https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/app.R#L369)
- patchwork used in [app.R](https://github.com/hirscheylab/ddh/blob/56cda91836d2cd95ba63c38502ce825c649740ee/code/report_depmap_app.Rmd#L14)
- viridis used in [methods.Rmd](https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/methods.Rmd#L15)
- pander used in [report_depmap_app.R](https://github.com/hirscheylab/ddh/blob/56cda91836d2cd95ba63c38502ce825c649740ee/code/report_depmap_app.Rmd#L13)

Removes shinyWidgets and causaleffect since they don't appear to be currently used.

Additional changes to fix issues deploying:
- rename markdown files to match actual case in code/app.R
- increases startup timeout to 180 seconds

Fixes #13

### CODE REVIEW

**Comment by matthewhirschey** [comment]
Looks OK. Could mention that this fixes issue  #13

**Comment by johnbradley** [comment]
> Looks OK. Could mention that this fixes issue #13

Done.

**Comment by matthewhirschey** [comment]
Can you also add the following to the docker file used to run the shiny webserver:

- DT used in app.R

This would fix and close issue #26 , I think.

**Review by dleehr — APPROVED** [review]

**Comment by johnbradley** [comment]
I added the DT library to Dockerfile.shiny.
Before #26 is completely fixed we will need a PR to merge this commit on develop into master:
https://github.com/hirscheylab/ddh/commit/2c91707903c0c33b2da0f6eb3bba6627e1ff0367

**Comment by dleehr** [comment]
I cherry-picked 2c91707 into this branch

**Review by matthewhirschey — APPROVED** [review]
LGTM

**Pull request merged**
