### PR TITLE
Issuer fixer

### PR DESCRIPTION
**Pull request by matthewhirschey**
This PR has two key changes.

1.  I realized that "ADIPOQ" was filtered from the data tables, but was still generating plots. This is because I was using the raw achilles data instead of the cleaned achilles data in these functions, leading to a discordance between the raw data and my cleaned data. The easiest and most logical fix is to not save the raw data as an object, and simply to called the cleaned data achilles. The raw data have a DOI (and therefore will always be available), and so I changed a few lines of code in the `generate_achilles_data.R` to create the achilles_raw object, and then move to achilles for the remainder of the analyses. The saved file output is still achilles.RData, and was only moved to the end to make sure all of the data transformations were accomplished before saving the file. This should not generate any extra files, and should properly called achilles.RData as the cleaned (not raw) data

2. Per @johnbradley suggestion, I added validation steps to make more informative error msgs. The  validation step checks to see if the gene_symbol is present in the dataframe.  If not found, then will stop the operation and display the custom message. I also needed to change how the text was displayed on the plot page so that it would accept a validate() argument. 

This should fix issue #41

### CODE REVIEW

**Review by dleehr — APPROVED** [review]
LGTM

**Review by johnbradley — COMMENTED** [review]
The changes here look good. 

The `Download Report` tab will still let a user click `Download report` after entering `ADIPOQ`.
The following is printed in the Console each time a user clicks `Download report`:
```
Warning: Error in : Unknown column `ADIPOQ` 
```

**Comment by matthewhirschey** [comment]
I tried. But...
1. Apparently validate() doesn't work inside of downloadHandler (see e.g. https://stackoverflow.com/questions/53616176/shiny-use-validate-inside-downloadhandler)

2. I also figured that by the time a user saw the messages that no data was available, she/he wouldn't try to download said file. 

This is mostly a UI/UX effort, not a strict 'prevent user from breaking system' effort. 

@johnbradley OK as is? Or other suggestions? I'm open.

**Comment by johnbradley** [comment]
> OK as is? Or other suggestions? I'm open.

I think it's OK as is. 

One option would be to have `render_report_to_file` call `render_dummy_report` when the gene is not found: 

https://github.com/hirscheylab/ddh/blob/9db9a648cfecc099c7ef2fe9a5595429ba1782b0/code/app.R#L311-L323

https://github.com/hirscheylab/ddh/blob/9db9a648cfecc099c7ef2fe9a5595429ba1782b0/code/app.R#L340-L344

I think the `render_dummy_report` change is outside of the focus of this PR. We can create an issue if we want to look into it later.

**Review by johnbradley — APPROVED** [review]
LGTM

**Comment by matthewhirschey** [comment]
@johnbradley, that's a great suggestion.

You previously created the render_dummy_report() as a test case when creating the initial skeleton. But I've since noticed that we don't call it ever. So this is a good solution, and easy to implement. I put the dummy_report.Rmd back in the code dir, added an if else statement that evaluates whether the gene name is in achilles, and then calls either the standard report or dummy report functions. I tested in TP53 to generate a normal report, and adipoq to generate a dummy report. I just pushed these changes.

**Comment by johnbradley** [comment]
Looks good. I tested these changes running locally and it worked great.

I think there might still be an issue with when we run in it production.
Previously we had to copy the Rmd template to a temp dir and then render it:
https://github.com/hirscheylab/ddh/blob/9db9a648cfecc099c7ef2fe9a5595429ba1782b0/code/app.R#L311-L323

**Comment by matthewhirschey** [comment]
You're correct. I didn't recall this error. 
The if/else should go in the parent function (render_report_to_file), not in the child function (render_complete_report OR render_dummy_report). Last commit does this. 

Good catch (again) @johnbradley

**Review by johnbradley — APPROVED** [review]

**Pull request merged**
