### PR TITLE
Lineage Plots

### PR DESCRIPTION
**Pull request by matthewhuang457**
Lineage and Sublineage boxplots for ddh

### CODE REVIEW

**Comment by matthewhirschey** [comment]
@matthewhuang457 
Two requested changes: 

1. The convention in this project is to generate all data in the generate data scripts, and then to load it in the app. You generate a data frame in the app. So please change. This code would probably go in `generate_depmap_data.R`. After moving the code there, then you can simply load the Rds file, as we've done for the others. 

2. Can you give the functions simpler and more intuitive names? Perhaps `make_lineage()` and `make_sublineage()`. I try to use "snake_case" instead of "camelCase", but this is a matter of style. And I"m trying to keep style the same.

**Comment by matthewhuang457** [comment]
@matthewhirschey Done!

**Review by matthewhirschey — APPROVED** [review]
Thanks for making these changes. 
Looks good to me.
Let's also wait for @johnbradley 's comments

**Review by johnbradley — APPROVED** [review]
LGTM (Looks good to me).

**Pull request merged**
