### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by matthewhirschey**
major updates include new 19Q4 data, and a few bug fixes to run it (remove line 46 in code/generate_depmap_data.R) 

Also included prototype to collect email address, and save to file in a conditionalPanel() for report generation. Could consider piping into SQL db, rather than file save.

### CODE REVIEW

**Review by johnbradley — CHANGES_REQUESTED** [review]
Good to see a fix for the cell_line issue mentioned here https://github.com/hirscheylab/ddh/issues/8#issuecomment-565594681.

Did you mean to include the code/responses/1576758136_5cde39d9e3e77c75a14e207ead015298.rds file in this PR? This is a data file that contains users email and name. Typically the `code` directory is read only in a deployment to prevent modifications. Long term we will need to look at storing these user emails somewhere that is backed up. We have issue #15 to figure out our long term plan for saving user emails/etc.

Change requested:
Can we save these user email address files into the `data` directory instead of `code`?

Thanks.

**Comment by matthewhirschey** [comment]
Great point @johnbradley 
Just pushed changes that fix the output dir (now called 'user') to the data dir. Do we need to make sure this dir exists and is writeable? Related to issue #15 

Also added a progress bar to the reporter generator

Note @dleehr: the app.R uses a new package (digest) on line 369 to generate a unique file name. This might be change in a later version, but please add install this package to the container

**Comment by johnbradley** [comment]
> Do we need to make sure this dir exists and is writeable?

Yes. In my testing `saveRDS` does not create directories if they do not exist. I think you could call `dir.create(...)` before calling `saveRDS`. As far as the writable part, the `data` directory is currently writeable in our deployment. I think the `data` directory was accidentally left writable. 

This code that saves the users info is a great start, but has several drawbacks that we can address via #15. Namely:
- security problems with writing files to a local directory via a webserver
- no backup for the data directory so we could potentially lose the user data files
- scaling up to multiple servers can have problems sharing a writable directory

There is no reason for the shiny server to modify any of the generated data files. Long term the data directory should be read only for the shiny server to prevent malicious or accidental modifications of the generated data files. Allowing a webserver to write files to disk can lead to security problems. For example a hacker might enter an R expression for their name which may allow them to run some code on our server.

**Review by johnbradley — APPROVED** [review]
Saving into SQL db rather than file save sounds like a much better way to go. 
We can address that in another PR.
This PR includes the upgrade to the `19Q4` data which will be good to have.

LGTM

**Pull request merged**
