### PR TITLE
Pathways

### PR DESCRIPTION
**Pull request by matthewhirschey**
This significant update adds the ability to search by a single gene (as before), pre-defined pathways (GO numbers), or a set of user defined genes. Landing pages were framed for each of these three options. All functions were updated to allow multiple gene inputs, and reports were standardized to accept each of the three types. 

Also added were these minor changes:
- Updated logo and landing page
- Made all URL links relative
- added Gene Link column in similar genes table to linkout
- added ability for user to define degree and threshold on network graph
- added GO term summaries for landing pages and reports
- added search logic to start with gene, then aka, then name, and rank by str_count
- added subcell map (need to install gganatogram package in container)
- added 'get lucky' which pre-populates search page with defined set of surprise genes (which have both pub index of <10 and >90 in top 10; as first pass) 
- re-org report functions to be own R script

### CODE REVIEW

**Review by johnbradley — APPROVED** [review]
LGTM

I added a commit to include new Dockerfile requirements.

**Comment by matthewhirschey** [comment]
Do you also need to load the gganatogram library into the docker file (in addition to installing the package?)

**Comment by johnbradley** [comment]
> Do you also need to load the gganatogram library into the docker file (in addition to installing the package?)

I don't understand. What do you mean by "load"? I thought installing the package was enough. I was able to run `library(gganatogram)` inside `R` within the Docker container.

**Comment by matthewhirschey** [comment]
never mind. I didn't know if you need to also load the library, not just install the package. I looked closer at the docker file and understand. The library is loaded in the shiny app. 🤦🏻‍♂️

**Pull request merged**
