### PR TITLE
Replaces web scraping entrez.Rmd with library based create_gene_summary

### PR DESCRIPTION
**Pull request by johnbradley**
Adds Rscript `code/create_gene_summary.R` that will create the `data/gene_summary.feather` file.
This major changes in this script compared to `entrez.Rmd` are:
- uses the rentrez library to fetch summaries
- instead of relying upon a pre-existing hugo.txt file it directly downloads data from genenames.org

This script takes around 2 hours to complete if run with an NCBI entrez key like so:
```
Rscript code/create_gene_summary.R --entrezkey YOURKEY
```
If you leave off the `--entrezkey YOURKEY` it will run fine but slower.
Details on creating an NCBI entrez key are at https://cran.r-project.org/web/packages/rentrez/vignettes/rentrez_tutorial.html

This change removes `code/entrez.Rmd` since it should be no longer needed.

I also included a Dockerfile that specifies the environment needed to run `create_gene_summary.R`.

### CODE REVIEW

**Comment by johnbradley** [comment]
@dleehr and @hlapp could you review my changes here? Thanks.

**Comment by hlapp** [comment]
@johnbradley can you assign us as reviewers?

**Comment by johnbradley** [comment]
> @johnbradley can you assign us as reviewers?

@hlapp Sorry I can't. The reviewers option is disabled for me on this PR.

**Comment by dleehr** [comment]
This change replaces an .Rmd document with an R script, but loses a lot of the documentation/simple comments that explain what the steps are and why. The purpose and usage details are here in the pull request, but would be more effective in the code - either in the script itself or a separate file.

I'll offer a suggestion: instead of removing the .Rmd file entirely, replace it with a short version that sources the functions from this R script and calls the functions. That would serve two purposes:

1. Documenting how to use the encapsulated function and explaining what to expect (runtime, parameters)
2. Providing a way to run it that's consistent with the rest of the code here.

I do not know what practice R users expect/prefer - do they expect to run scripts from the command-line with argument parsing, or do they prefer to `source()` functions from other scripts?

**Pull request merged**
